# Generated by Django 3.2 on 2021-04-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prisoner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nome')),
                ('matriculation', models.CharField(max_length=9, verbose_name='Matrícula')),
            ],
            options={
                'verbose_name': 'Sentenciado',
                'verbose_name_plural': 'Sentenciados',
            },
        ),
    ]
