# Generated by Django 3.2 on 2021-04-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210429_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='prisoner',
            name='excluded',
            field=models.DateField(blank=True, null=True, verbose_name='Excluído'),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='included',
            field=models.DateField(blank=True, null=True, verbose_name='Incluído'),
        ),
    ]
